/* deck.h — the card decks for truth-or-dare, split into three spice tiers.
 *
 * The font is uppercase A-Z and 0-9 only, so every card is written that way:
 * punctuation would render as blanks and read as ragged gaps.  Cards are kept
 * under about sixty characters so they wrap to at most five lines at scale 2.
 *
 * Content rules the decks stick to, since this gets handed round a room of
 * people and the device cannot read tone:
 *   - nothing that needs alcohol or any substance to play
 *   - nothing physically risky, and nothing that damages property
 *   - nothing contacting an ex or a stranger, which lands on someone who
 *     never agreed to play
 *   - bold at the expense of the person holding the device, not at the
 *     expense of someone else in the room
 * UNHINGED gets more exposing, not more harmful.  That is the whole trick.
 */
#ifndef DECK_H
#define DECK_H

/* ── MILD ─────────────────────────────────────────────────────────── */
static const char* const truth_mild[] = {
    "WHAT IS THE LAST THING YOU SEARCHED FOR",
    "WHAT IS YOUR MOST USELESS TALENT",
    "WHO HERE WOULD YOU CALL IN A CRISIS",
    "WHAT SONG DO YOU PLAY ON REPEAT",
    "WHAT IS THE WORST HAIRCUT YOU EVER HAD",
    "WHAT APP DO YOU WASTE THE MOST TIME ON",
    "WHAT IS THE PETTIEST HILL YOU WILL DIE ON",
    "WHAT IS YOUR WORST HABIT",
    "WHO HERE HAS THE BEST TASTE IN MUSIC",
    "WHAT IS THE WEIRDEST THING IN YOUR BAG",
    "WHAT MOVIE DOES EVERYONE LOVE THAT YOU HATE",
    "WHAT IS YOUR GO TO KARAOKE SONG",
    "WHAT IS THE LAST PHOTO IN YOUR CAMERA ROLL",
    "WHAT CHILDHOOD SHOW DO YOU STILL LOVE",
    "WHAT IS YOUR MOST IRRATIONAL FEAR",
    "WHO HERE WOULD SURVIVE A ZOMBIE MOVIE",
    "WHAT IS THE BEST GIFT YOU EVER GOT",
    "WHAT ARE YOU WEIRDLY COMPETITIVE ABOUT",
};

static const char* const dare_mild[] = {
    "TALK IN AN ACCENT UNTIL YOUR NEXT TURN",
    "DO YOUR BEST IMPRESSION OF SOMEONE HERE",
    "LET THE GROUP PICK THE NEXT SONG",
    "DO 10 PUSHUPS RIGHT NOW",
    "SPEAK ONLY IN QUESTIONS FOR 2 MINUTES",
    "SHOW THE LAST 3 PHOTOS IN YOUR CAMERA ROLL",
    "DANCE WITH NO MUSIC FOR 20 SECONDS",
    "SAY THE ALPHABET BACKWARDS",
    "DO A DRAMATIC READING OF YOUR LAST TEXT",
    "SWAP ONE ITEM OF CLOTHING WITH SOMEONE",
    "BALANCE SOMETHING ON YOUR HEAD FOR A MINUTE",
    "GIVE EVERYONE HERE A NEW NICKNAME",
    "TALK WITHOUT USING THE LETTER E",
    "DO YOUR BEST RUNWAY WALK",
    "COMPLIMENT EVERYONE IN THE ROOM",
    "HOLD A PLANK UNTIL YOUR NEXT TURN",
    "LET SOMEONE ADD A CONTACT NAME TO YOUR PHONE",
    "ACT OUT YOUR MORNING ROUTINE IN SILENCE",
};

/* ── SPICY ────────────────────────────────────────────────────────── */
static const char* const truth_spicy[] = {
    "WHO HERE WOULD YOU SWAP LIVES WITH",
    "WHAT IS THE BIGGEST LIE YOU HAVE TOLD",
    "WHAT IS YOUR MOST EMBARRASSING PARTY STORY",
    "WHAT IS A SECRET NOBODY HERE KNOWS",
    "WHO HERE DO YOU FIND MOST ATTRACTIVE",
    "HAVE YOU EVER FAKED BEING SICK TO AVOID SOMEONE",
    "WHAT IS YOUR MOST TOXIC TRAIT",
    "WHAT IS THE PETTIEST REASON YOU DUMPED SOMEONE",
    "WHAT IS THE WORST TEXT YOU SENT BY MISTAKE",
    "WHO IS YOUR CELEBRITY FREE PASS",
    "WHAT IS THE DUMBEST REASON YOU HAVE CRIED",
    "WHAT IS THE MOST MONEY YOU HAVE WASTED",
    "WHO HERE WOULD YOU TRUST WITH YOUR PHONE UNLOCKED",
    "WHAT RUMOUR ABOUT YOU IS ACTUALLY TRUE",
    "WHAT IS THE WORST DATE YOU HAVE BEEN ON",
    "WHO HERE ARE YOU MOST LIKELY TO ENVY",
    "WHAT COMPLIMENT DO YOU FISH FOR",
    "WHAT IS SOMETHING YOU PRETEND TO ENJOY",
};

static const char* const dare_spicy[] = {
    "LET SOMEONE READ YOUR LAST 5 TEXTS ALOUD",
    "SHOW YOUR SEARCH HISTORY TO THE PERSON LEFT",
    "LET SOMEONE DRAW ON YOUR FACE",
    "READ YOUR LAST SENT MESSAGE OUT LOUD",
    "SWAP PHONES WITH SOMEONE FOR 5 MINUTES",
    "TELL A SECRET OR TAKE TWO MORE DARES",
    "LET SOMEONE STYLE YOUR HAIR HOWEVER THEY WANT",
    "RATE EVERYONE HERE OUT OF 10 OUT LOUD",
    "CONFESS SOMETHING TO THE PERSON ON YOUR RIGHT",
    "LET THE GROUP CHOOSE YOUR OUTFIT FOR TOMORROW",
    "DO YOUR BEST FLIRT ON THE NEAREST OBJECT",
    "SAY SOMETHING YOU HAVE NEVER ADMITTED HERE",
    "LET SOMEONE SCROLL YOUR PHOTOS FOR 30 SECONDS",
    "SING A CHORUS AS A VOICE NOTE TO THE GROUP",
    "LET THE GROUP PICK YOUR PROFILE PICTURE",
    "IMITATE THE PERSON ON YOUR LEFT UNTIL GUESSED",
    "ANSWER THE NEXT 3 QUESTIONS WITH FULL HONESTY",
    "LET SOMEONE ASK YOU ONE QUESTION YOU MUST ANSWER",
};

/* ── UNHINGED ─────────────────────────────────────────────────────── */
static const char* const truth_wild[] = {
    "WHAT IS THE WORST THING YOU HAVE EVER SEARCHED",
    "WHO HERE WOULD YOU LEAVE BEHIND TO SURVIVE",
    "WHAT IS THE MOST UNHINGED THING IN YOUR NOTES APP",
    "WHO HERE HAVE YOU HAD A DREAM ABOUT",
    "WHAT IS YOUR VILLAIN ORIGIN STORY",
    "WHO HERE WOULD YOU NEVER SHARE A ROOM WITH",
    "WHAT IS THE PETTIEST REVENGE YOU HAVE TAKEN",
    "WHAT HAVE YOU THOUGHT ABOUT SOMEONE IN THIS ROOM",
    "WHAT IS THE WORST LIE YOU TOLD YOUR PARENTS",
    "WHAT WOULD RUIN YOU IF IT GOT OUT",
    "WHO HERE IS MOST LIKELY TO GET ARRESTED",
    "WHAT IS THE WEIRDEST THING YOU FIND ATTRACTIVE",
    "WHAT IS THE WORST THING YOU HAVE SAID OUT LOUD",
    "WHO HERE WOULD YOU FIGHT AND ACTUALLY BEAT",
    "WHAT IS YOUR MOST DELUSIONAL BELIEF ABOUT YOURSELF",
    "WHAT IS THE MOST EMBARRASSING THING YOU OWN",
    "WHAT IS A GRUDGE YOU ARE STILL HOLDING",
    "WHAT IS THE CRINGIEST THING YOU HAVE EVER POSTED",
};

static const char* const dare_wild[] = {
    "LET THE GROUP SEND ONE TEXT AS YOU NO EDITS",
    "SHOW THE WORST PHOTO ON YOUR PHONE",
    "LET SOMEONE REWRITE YOUR BIO FOR A WEEK",
    "LET THE GROUP READ YOUR NOTES APP",
    "LET SOMEONE PICK A TATTOO IDEA AND DRAW IT ON YOU",
    "ANSWER AS SOMEONE HERE FOR THE NEXT 5 MINUTES",
    "LET THE GROUP NAME YOU FOR THE REST OF TONIGHT",
    "CONFESS YOUR WORST OPINION AND DEFEND IT",
    "LET SOMEONE SCROLL YOUR FOLLOWING LIST",
    "ACT OUT YOUR MOST EMBARRASSING MEMORY",
    "LET THE GROUP SET YOUR LOCK SCREEN FOR A WEEK",
    "SAY THE MEANEST TRUE THING ABOUT YOURSELF",
    "LET SOMEONE PICK WHAT YOU WEAR FROM THIS ROOM",
    "ROAST YOURSELF FOR 30 SECONDS STRAIGHT",
    "REVEAL YOUR MOST RECENT REGRET IN DETAIL",
    "LET EACH PERSON ASK YOU ONE THING NO PASSING",
    "READ YOUR OLDEST SAVED MESSAGE OUT LOUD",
    "TELL THE GROUP WHAT YOU REALLY THINK OF THIS GAME",
};

#define DECK_N 18u

static const char* const* const g_truth[3] = { truth_mild, truth_spicy, truth_wild };
static const char* const* const g_dare[3]  = { dare_mild,  dare_spicy,  dare_wild  };

#endif /* DECK_H */
